# tested on 3090 w bsz 1, 4, 8, nvidia driver 535 
torchrun --standalone --nproc_per_node 4 torchrun_main.py \
    --model_config configs/llama_7b.json \
    --lr 0.0001 \
    --galore_scale 0.25 \
    --rank 1024 \
    --update_proj_gap 10000 \
    --batch_size 32 \
    --total_batch_size 512 \
    --num_training_steps 150000 \
    --warmup_steps 15000 \
    --dtype bfloat16 \
    --eval_every 1000 \
    --optimizer adam8bit \
    --lora_alpha 0.5 \
    --bnb_4bit_quant_type nf4 \
    --quantize_w '4bit' \
    --quantize_projection_matrix '4bit' \
    --seed 42 \
    --save_every 1000 \
    --save_dir checkpoints/llama2_7b_c4 \
    --proj_gap_progression "exponential" \
    --increment_size 1.15 \
    --name llam2_7b_1.15_100_c4 \
    --use_offloading True \
    --use_double_quant True \
    --use_loqt True 